# Generated by Django 5.0.8 on 2025-12-15 12:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Слаг (URL)')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='news/covers/%Y/%m/', verbose_name='Обложка')),
                ('body', models.TextField(blank=True, verbose_name='Текст')),
                ('badge', models.CharField(blank=True, max_length=30, verbose_name='Бейдж (например: ВАЖНО / ПОДАРОК)')),
                ('card_style', models.CharField(choices=[('default', 'Обычная'), ('important', 'Важно'), ('gift', 'Подарок'), ('month', 'Месяц')], default='default', max_length=16, verbose_name='Стиль карточки')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['is_published', 'published_at'], name='news_pub_idx')],
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news/photos/%Y/%m/', verbose_name='Фото')),
                ('caption', models.CharField(blank=True, max_length=120, verbose_name='Подпись (необязательно)')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='news.newspost', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Фото новости',
                'verbose_name_plural': 'Фото новости',
                'ordering': ['sort', 'id'],
            },
        ),
    ]
