# Generated by Django 5.0.8 on 2025-12-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_card_design'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='badge',
            field=models.CharField(blank=True, max_length=30, verbose_name='Бейдж (необязательно)'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='title',
            field=models.CharField(max_length=180, verbose_name='Заголовок (полный)'),
        ),
    ]
