# Generated by Django 5.0.8 on 2026-02-19 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("loyalty", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LoyaltyProfile",
        ),
        migrations.CreateModel(
            name="CashbackBonus",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_type", models.CharField(db_index=True, default="", max_length=32)),
                ("source_id", models.PositiveBigIntegerField(db_index=True)),
                ("base_amount", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("remaining_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("reason", models.CharField(blank=True, default="", max_length=255)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cashback_bonuses", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "verbose_name": "Кэшбек-бонус",
                "verbose_name_plural": "Кэшбек-бонусы",
                "ordering": ("expires_at", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="CashbackBonusSpend",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_type", models.CharField(db_index=True, default="", max_length=32)),
                ("source_id", models.PositiveBigIntegerField(db_index=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("reason", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bonus",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="spends", to="loyalty.cashbackbonus"),
                ),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cashback_bonus_spends", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "verbose_name": "Списание кэшбек-бонусов",
                "verbose_name_plural": "Списания кэшбек-бонусов",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddConstraint(
            model_name="cashbackbonus",
            constraint=models.UniqueConstraint(fields=("user", "source_type", "source_id"), name="uniq_cashback_bonus_source"),
        ),
        migrations.AddIndex(
            model_name="cashbackbonus",
            index=models.Index(fields=["user", "expires_at"], name="cashback_user_exp_idx"),
        ),
        migrations.AddIndex(
            model_name="cashbackbonusspend",
            index=models.Index(fields=["user", "source_type", "source_id"], name="cashback_spend_src_idx"),
        ),
    ]
