# Generated by Django 5.0.8 on 2025-12-13 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('membership_status', models.CharField(blank=True, max_length=64)),
                ('payment_status', models.CharField(blank=True, max_length=64)),
                ('composition_raw', models.CharField(blank=True, max_length=255)),
                ('total_visits', models.PositiveIntegerField(blank=True, null=True)),
                ('left_visits', models.PositiveIntegerField(blank=True, null=True)),
                ('used_visits', models.PositiveIntegerField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('purchased_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(default='appevent', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
