# Generated by Django 5.0.8 on 2025-12-14 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Активен'), ('frozen', 'Заморожен'), ('expired', 'Истёк'), ('canceled', 'Отменён')], default='active', max_length=16)),
                ('payment_status', models.CharField(choices=[('paid', 'Оплачен'), ('unpaid', 'Не оплачен'), ('partial', 'Частично')], default='paid', max_length=16)),
                ('total_visits', models.PositiveIntegerField(blank=True, null=True)),
                ('left_visits', models.PositiveIntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
