# Generated by Django 5.0.8 on 2025-12-14 04:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'verbose_name': 'Абонемент', 'verbose_name_plural': 'Абонементы'},
        ),
        migrations.AlterField(
            model_name='membership',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Окончание'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='left_visits',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Осталось посещений'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='note',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Оплачен'), ('unpaid', 'Не оплачен'), ('partial', 'Частично')], default='paid', max_length=16, verbose_name='Статус оплаты'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('frozen', 'Заморожен'), ('expired', 'Истёк'), ('canceled', 'Отменён')], default='active', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='total_visits',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Всего посещений'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
    ]
