# Generated by Django 5.0.8 on 2026-01-30 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0003_alter_membership_options_remove_membership_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='scope',
            field=models.CharField(blank=True, choices=[('group', 'Групповые'), ('personal', 'Персональные')], default='', help_text='group/personal (можно оставить пустым для совместимости со старыми данными)', max_length=16),
        ),
    ]
