# Generated by Django 5.0.8 on 2026-02-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memberships", "0004_membership_scope"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="validity_days",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Срок действия в днях. Отсчёт начинается с первого использования.",
                null=True,
            ),
        ),
    ]
