# Generated by Django 5.0.8 on 2025-12-14 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='attendance_status',
            field=models.CharField(choices=[('unknown', 'Не отмечено'), ('attended', 'Пришел'), ('noshow', 'Не пришел')], default='unknown', max_length=16),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('booked', 'Записан'), ('canceled', 'Отменен'), ('waitlist', 'Лист ожидания')], default='booked', max_length=16),
        ),
        migrations.AddField(
            model_name='booking',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='marked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
