# Generated by Django 5.0.8 on 2025-12-14 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
        ('schedule', '0002_booking_attendance_status_booking_booking_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='memberships.membership'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='attendance_status',
            field=models.CharField(choices=[('unknown', 'Не отмечено'), ('attended', 'Пришёл'), ('noshow', 'Не пришёл')], default='unknown', max_length=16),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('booked', 'Записан'), ('canceled', 'Отменён'), ('waitlist', 'Лист ожидания')], default='booked', max_length=16),
        ),
    ]
