# Generated by Django 5.0.8 on 2025-12-14 04:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_alter_membership_options_alter_membership_created_at_and_more'),
        ('schedule', '0003_booking_membership_alter_booking_attendance_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name': 'Занятие', 'verbose_name_plural': 'Занятия'},
        ),
        migrations.AlterModelOptions(
            name='trainer',
            options={'verbose_name': 'Тренер', 'verbose_name_plural': 'Тренеры'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='attendance_status',
            field=models.CharField(choices=[('unknown', 'Не отмечено'), ('attended', 'Пришёл'), ('noshow', 'Не пришёл')], default='unknown', max_length=16, verbose_name='Посещение'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('booked', 'Записан'), ('canceled', 'Отменён'), ('waitlist', 'Лист ожидания')], default='booked', max_length=16, verbose_name='Статус записи'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Отменено'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='marked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Отмечено'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='memberships.membership', verbose_name='Абонемент'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='schedule.session', verbose_name='Занятие'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='session',
            name='capacity',
            field=models.PositiveIntegerField(default=20, verbose_name='Вместимость'),
        ),
        migrations.AlterField(
            model_name='session',
            name='duration_min',
            field=models.PositiveIntegerField(default=50, verbose_name='Длительность (мин)'),
        ),
        migrations.AlterField(
            model_name='session',
            name='location',
            field=models.CharField(blank=True, max_length=140, verbose_name='Адрес/зал'),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_at',
            field=models.DateTimeField(verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='session',
            name='title',
            field=models.CharField(max_length=140, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='session',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='schedule.trainer', verbose_name='Тренер'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Имя'),
        ),
    ]
