# Generated by Django 5.0.8 on 2025-12-15 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_alter_membership_options_alter_membership_created_at_and_more'),
        ('schedule', '0005_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['start_at'], 'verbose_name': 'Занятие', 'verbose_name_plural': 'Занятия'},
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='attendance_status',
            field=models.CharField(choices=[('not_marked', 'Не отмечено'), ('attended', 'Посетил'), ('missed', 'Не пришёл')], db_index=True, default='not_marked', max_length=16, verbose_name='Посещаемость'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('booked', 'Записан'), ('canceled', 'Отменён')], db_index=True, default='booked', max_length=16, verbose_name='Статус записи'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='memberships.membership', verbose_name='Абонемент'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='session',
            name='duration_min',
            field=models.PositiveIntegerField(default=50, verbose_name='Длительность, мин'),
        ),
        migrations.AlterField(
            model_name='session',
            name='location',
            field=models.CharField(db_index=True, max_length=160, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_at',
            field=models.DateTimeField(db_index=True, verbose_name='Дата/время'),
        ),
        migrations.AlterField(
            model_name='session',
            name='title',
            field=models.CharField(max_length=160, verbose_name='Название'),
        ),
    ]
