# Generated by ChatGPT on 2026-02-10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0007_session_kind_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="invite_sent_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Приглашение отправлено"),
        ),
        migrations.AddField(
            model_name="booking",
            name="invite_expires_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Приглашение истекает"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="booking_status",
            field=models.CharField(
                choices=[
                    ("booked", "Записан"),
                    ("waitlist", "Лист ожидания"),
                    ("invited", "Приглашён"),
                    ("canceled", "Отменён"),
                ],
                db_index=True,
                default="booked",
                max_length=16,
                verbose_name="Статус записи",
            ),
        ),
        migrations.CreateModel(
            name="PaymentIntent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount_rub", models.PositiveIntegerField(default=0, verbose_name="Сумма, руб")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новый"),
                            ("pending", "Ожидает оплату"),
                            ("paid", "Оплачен"),
                            ("canceled", "Отменён"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=12,
                    ),
                ),
                ("tb_payment_id", models.CharField(blank=True, default="", max_length=64, verbose_name="TBank payment id")),
                ("tb_status", models.CharField(blank=True, default="", max_length=32, verbose_name="TBank status")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_intents",
                        to="schedule.session",
                        verbose_name="Занятие",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_payment_intents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Оплата занятия",
                "verbose_name_plural": "Оплаты занятий",
            },
        ),
        migrations.AddIndex(
            model_name="paymentintent",
            index=models.Index(fields=["status", "created_at"], name="pi_status_created_idx"),
        ),
        migrations.AddIndex(
            model_name="paymentintent",
            index=models.Index(fields=["user", "created_at"], name="pi_user_created_idx"),
        ),
    ]
