# Generated by Django 5.0.8 on 2026-01-27 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('section', 'sort', 'name')},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('sort', 'name')},
        ),
        migrations.AddField(
            model_name='category',
            name='section',
            field=models.CharField(choices=[('memberships', 'Абонементы'), ('personal', 'Персональные'), ('group', 'Групповые'), ('other', 'Прочее')], db_index=True, default='group', max_length=16),
        ),
        migrations.AddField(
            model_name='product',
            name='badge',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shop/'),
        ),
        migrations.AddField(
            model_name='product',
            name='sort',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='product',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
    ]
