# Generated by Django 5.0.8 on 2026-01-27 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_options_alter_product_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_trial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='trial_scope',
            field=models.CharField(blank=True, choices=[('group', 'Пробное (групповое)'), ('personal', 'Пробное (персональное)')], default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='product',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.CreateModel(
            name='TrialUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('group', 'Пробное (групповое)'), ('personal', 'Пробное (персональное)')], max_length=16)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_uses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'scope')},
            },
        ),
    ]
