# Generated by Django 5.0.8 on 2026-01-30 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_is_trial_product_trial_scope_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='grant_kind',
            field=models.CharField(choices=[('none', 'Не выдаёт ничего'), ('membership', 'Выдаёт абонемент'), ('wallet_topup', 'Пополняет кошелёк')], db_index=True, default='none', max_length=16),
        ),
        migrations.AddField(
            model_name='product',
            name='membership_days',
            field=models.PositiveIntegerField(blank=True, help_text='Срок действия в днях (если TIME/UNLIMITED).', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='membership_kind',
            field=models.CharField(blank=True, choices=[('visits', 'По посещениям'), ('time', 'По времени'), ('unlimited', 'Безлимит')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='product',
            name='membership_scope',
            field=models.CharField(blank=True, choices=[('group', 'Групповые'), ('personal', 'Персональные')], default='', help_text='Для каких тренировок работает абонемент (group/personal).', max_length=16),
        ),
        migrations.AddField(
            model_name='product',
            name='membership_visits',
            field=models.PositiveIntegerField(blank=True, help_text='Сколько посещений выдаём (если VISITS).', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='wallet_topup_rub',
            field=models.PositiveIntegerField(blank=True, help_text='Сколько рублей начислить в кошелёк.', null=True),
        ),
    ]
